function Hd = butter_lp3
%BUTTER_LP3 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 24.1 and DSP System Toolbox 24.1.
% Generated on: 21-Nov-2025 15:27:40

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
Fs = 8000;  % Sampling Frequency

N  = 3;     % Order
Fc = 1500;  % Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass('N,F3dB', N, Fc, Fs);
Hd = design(h, 'butter');

% [EOF]

fvtool(Hd);

figure;
[impResp, n] = impz(Hd);  % Compute impulse response
stem(n, impResp, 'filled');  % Stem plot
title('Impulse Response of the Filter');
xlabel('Sample n');
ylabel('Amplitude');
grid on;

figure;
[stepResp, n] = stepz(Hd);  % Compute step response
stem(n, stepResp, 'filled');  % Stem plot
title('Step Response of the Filter');
xlabel('Sample n');
ylabel('Amplitude');
grid on;

